const ALERT = "ALERT";
const REFREST_CHAT = "REFREST_CHAT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";


export { ALERT, REFREST_CHAT, NEW_MESSAGE_ALERT, NEW_ATTACHMENT };
